export const US_STATE_OPTIONS = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];

export const COMMON_COUNTY_OPTIONS_BY_STATE: Record<string, string[]> = {
  SC: [
    "Abbeville County",
    "Aiken County",
    "Allendale County",
    "Anderson County",
    "Bamberg County",
    "Barnwell County",
    "Beaufort County",
    "Berkeley County",
    "Calhoun County",
    "Charleston County",
    "Cherokee County",
    "Chester County",
    "Chesterfield County",
    "Clarendon County",
    "Colleton County",
    "Darlington County",
    "Dillon County",
    "Dorchester County",
    "Edgefield County",
    "Fairfield County",
    "Florence County",
    "Georgetown County",
    "Greenville County",
    "Greenwood County",
    "Hampton County",
    "Horry County",
    "Jasper County",
    "Kershaw County",
    "Lancaster County",
    "Laurens County",
    "Lee County",
    "Lexington County",
    "Marion County",
    "Marlboro County",
    "McCormick County",
    "Newberry County",
    "Oconee County",
    "Orangeburg County",
    "Pickens County",
    "Richland County",
    "Saluda County",
    "Spartanburg County",
    "Sumter County",
    "Union County",
    "Williamsburg County",
    "York County",
  ],
  TX: [
    "Anderson County",
    "Bell County",
    "Bexar County",
    "Bowie County",
    "Brazoria County",
    "Brown County",
    "Burleson County",
    "Callahan County",
    "Coke County",
    "Coleman County",
    "Comanche County",
    "Dallas County",
    "Denton County",
    "Eastland County",
    "Ellis County",
    "Erath County",
    "Fannin County",
    "Fort Bend County",
    "Grayson County",
    "Harris County",
    "Hays County",
    "Henderson County",
    "Hill County",
    "Hood County",
    "Hopkins County",
    "Hunt County",
    "Johnson County",
    "Kaufman County",
    "Lamar County",
    "Lampasas County",
    "Leon County",
    "Limestone County",
    "Mason County",
    "McCulloch County",
    "Mills County",
    "Montague County",
    "Navarro County",
    "Palo Pinto County",
    "Parker County",
    "Rains County",
    "Robertson County",
    "Rockwall County",
    "San Saba County",
    "Somervell County",
    "Stephens County",
    "Tarrant County",
    "Taylor County",
    "Travis County",
    "Van Zandt County",
    "Wise County",
  ],
};
